#
#

trigger:
- MS-Sample

pool:
  vmlmage: ubuntuâ€”latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'